apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-java-app
  labels:
    app: sample-java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-java-app
  template:
    metadata:
      labels:
        app: sample-java-app
    spec:
      containers:
      - name: sample-java-app
        image: rs871997/sample-java-project:2.0
        ports:
        - containerPort: 8050
---
apiVersion: v1
kind: Service
metadata:
  name: sample-java-app-service
spec:
  selector:
    app: sample-java-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8050
  type: ClusterIP
